### ISSUE TITLE
Multiple: (non-monster) icons on EDGE don't appear

### ISSUE THREAD

**Issue by basvandepol92** [codezilla-nl/codezilla-website#121]
Icons on 'Visie' and 'Werken bij' page don't appear on EDGE.

**VISIE:**
<img width="978" alt="screen shot 2018-03-30 at 11 26 32 am" src="https://user-images.githubusercontent.com/26919235/38132895-3b1e27ea-340d-11e8-8fcd-62e3a7871711.png">

**WERKEN BIJ:**
<img width="883" alt="screen shot 2018-03-30 at 11 26 19 am" src="https://user-images.githubusercontent.com/26919235/38132896-3b466070-340d-11e8-9dcb-3ca089e84564.png">

**Comment by jellekralt** [comment]
Fixed in #127
