### ISSUE TITLE
npm install fails on latest Node LTS

### ISSUE THREAD

**Issue by developenguin** [codezilla-nl/codezilla-website#263]
NPM install fails when the latest Node LTS (16 at the time of writing) is active on the system. I haven't tested other scripts.
Node v14 also fails, 12 seems to work.

**Comment by patrickkraaij** [comment]
I will look into this. I'm gonna aim for the latest LTS.

**Comment by patrickkraaij** [comment]
I've added a Pull Request:
https://github.com/codezilla-nl/codezilla-website/pull/265

**Comment by patrickkraaij** [comment]
Pull Request is merged, so this issue can be closed.
