### ISSUE TITLE
Header wider than viewport

### ISSUE THREAD

**Issue by nicoes** [codezilla-nl/codezilla-website#41]
I noticed that the header (with slider) is wider than the viewport. This creates a horizontal scroll bar. @hvgeertruy. Could you look into this?

**Comment by nicoes** [comment]
@jellekralt deze is gefixed toch?

**Comment by jellekralt** [comment]
Yup, should be automatically fixed because I've set a overflow-x: hidden on the page container (needed for the navigation)
