### ISSUE TITLE
Werken bij: 'jij-hier?' image does have a pointer cursor when hovering

### ISSUE THREAD

**Issue by patrickkraaij** [codezilla-nl/codezilla-website#81]
When hover over the 'jij-hier?' image at 'Werken Bij', the cursor shows a pointer but it does not have an anchor. We should remove the ```cz-diamond--clickable``` class.
![hover-niet-op-jij-hier-avatar](https://user-images.githubusercontent.com/618788/26946433-86b196ee-4c8f-11e7-9e62-1753a59f2767.gif)

**Comment by jellekralt** [comment]
Fixed in #89
